mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', include('notes.urls')),
    path('admin/', admin.site.urls),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('', include('django.contrib.auth.urls')),
]

notes/urls.py
from django.urls import path
from notes import views

app_name = 'notes'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name="login"),
    path('home/', views.home, name="home"),
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('create_note/', views.CreateNoteView.as_view(), name="create_note"),
    path('display_notes/', views.display_notes, name="display_notes")
    ]

notes/models.py
from django.contrib.auth.models import User
from django.db import models
from mysite import settings


class Note(models.Model):
    user=models.ForeignKey(User, on_delete=models.CASCADE)
    title=models.CharField('Title', max_length=100, blank=True, null=True)
    note=models.CharField('Note', max_length=1000, blank=True, null=True)

notes/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms import TextInput, Select

from notes.models import Note


class UserCreationForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password']


class UserNotesForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['user', 'title', 'note']
        widgets = {
            'title': TextInput(attrs={'placeholder': 'Note title', 'class': 'form-control'}),
            'note': TextInput(attrs={'placeholder': '', 'Note': 'form-control'}),
        }

notes/views.py
from django.contrib import auth
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from django.views.generic import CreateView

from notes.forms import UserNotesForm
from notes.models import Note


def login(request):
    if request.method == 'POST':
        user = auth.authenticate(username=request.POST['username'], password=request.POST['password'])
        if user is not None:
            auth.login(request, user)
            return redirect('notes:home')
        else:
            return render(request, 'registration/login.html', {'error': 'username or password incorrect.'})
    else:
        return render(request, 'registration/login.html')


def index(request):
    return render(request, 'index.html')


def edit_note(request):
    context={

    }
    return render(request, 'display_notes.html', context)

@login_required
def home(request):
    current_user = request.user
    context = {'current_user': current_user}
    return render(request, 'home.html', context)


@login_required
def display_notes(request):
    current_user = request.user.username
    current_user_id = User.objects.get(username=current_user)
    user_notes = Note.objects.filter(user_id=current_user_id)
    context = {
        'user_notes': user_notes,
        'current_user': current_user,
    }
    return render(request, 'display_notes.html', context)


class SignupView(CreateView):
    model = User
    form_class = UserCreationForm
    template_name = 'signup.html'

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect('login')


class CreateNoteView(CreateView):
    model = Note
    form_class = UserNotesForm
    template_name = 'create_note.html'

    def form_valid(self, form):
        if form.is_valid():
            form.save()
            return redirect('notes:home')

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Write your note here!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <style type="text/css">
        html,
        body,
        header,
        .navbar {
            background-color: #333;
            overflow: hidden;
        }

        .navbar a {
            -webkit-border-radius: 8px;
            -moz-border-radius: 8px;
            border-radius: 8px;
        }

        .navbar a:hover {
            background-color: mediumseagreen;
        }

        div.navbar-end a {
            float: left !important;
            color: #f2f2f2;
            text-align: left;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
            align-content: center;
        }

        .navbar-right {
            background-color: #333;
            overflow: hidden;
        }

        .navbar-left {
            background-color: #333;
            overflow: hidden;
        }

        div .navbar-right a {
            display: inline-block;
            color: white;
            float: right;
            padding: 14px;
            text-decoration: none;
            text-align: center;
        }

        div .navbar-left a {
            display: inline-block;
            color: white;
            float: left;
            padding: 14px;
            text-decoration: none;
            text-align: center;
        }

        .note {
            height: 25vw;
            width: 25vw;
            background: seagreen;
            display: inline-block;
            text-align: center;
            line-height: 5vw;
            margin: 30px 50px;
            position: relative;
        }

        div .note-title {
            height: 5vw;
            width: 25vw;
            background: #4CAF50;
            font-size: 2vw;
        }

        div .note-content {
            height: 20vw;
            width: 25vw;
            font-size: 1vw;
        }


        .wrapper {
            width: 800px;
            height: 200px;
            line-height: 200px;

            top: 30%;
            margin-top: -100px;
            left: 50%;
            margin-left: -400px;
            font-weight: bold;
            font-size: 100px;
            text-align: center
        }

        div .button-wrapper {
            position: absolute;
            right: 0;
            bottom: 0;
        }

        .square-button {
            border-radius: 2px;
            position: relative;
        }

    </style>
</head>

<body>
<div class="container-fluid pb-5">
    <nav class="navbar navbar-dark">
        <div class="navbar-left">
            <a class="navbar-brand waves-effect" href="https://mdbootstrap.com/docs/jquery/" target="_blank">
                <strong class="text-white">WELCOME TO NOTES!</strong>
            </a>
            {% if request.user.is_authenticated %}
                <a href="{% url 'notes:home' %}" class="navbar-item">
                    Home
                </a>
                <a href="{% url 'notes:display_notes' %}" class="navbar-item">
                    My Notes
                </a>
            {% endif %}
        </div>

        <div class="navbar-right">
            {% if request.user.is_authenticated %}
                <a href="{% url 'logout' %}" class="navbar-item">
                    Log Out
                </a>
                <nav class="navbar">
                    <span class="navbar-text">
                         <b> {{ user.username }} </b>
                    </span>
                </nav>
            {% else %}
                <a href="{% url 'notes:login' %}" class="navbar-item">
                    Log In
                </a>
                <a href="{% url 'notes:signup' %}" class="navbar-item">
                    <strong>Sign Up</strong>
                </a>
            {% endif %}

            {% if request.user.is_authenticated %}

            {% endif %}
        </div>
    </nav>
</div>

<div class="container-fluid">
    <div>
        {% block content %}

        {% endblock %}
    </div>
</div>

</body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</html>

templates/create_note.html
<!-- templates/home.html-->

{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="col-sm-20 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin d-inline-block bg-dark text-lg-center">
                    <div>
                        <form method="post" action="{% url 'notes:create_note' %}">
                            {% csrf_token %}
                            {{ form|crispy }}
                            <input class="btn btn-primary" type="submit" value="POST IT">
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/display_notes.html
<!-- templates/display_notes.html-->

{% extends 'base.html' %}

{% block content %}
    {% if user.is_authenticated %}
        {% csrf_token %}
        <form method="get" action="{% url 'notes:display_notes' %}">
            {% for item in user_notes %}
                <div class="note">
                    <div class="note-title">
                        {{ item.title }}
                    </div>
                    <div class="note-content">
                        {{ item.note }}
                        <form method="get" action="{% url 'notes:display_notes' %}">
                            <div class="button-wrapper">
                            <square-button type="submit" class="btn btn-success">
                                Edit
                            </square-button>
                        </div>
                        </form>
                    </div>
                </div>
            {% endfor %}
        </form>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">login </a>
    {% endif %}
{% endblock %}

templates/home.html
<!-- templates/home.html-->

{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
    <div class="wrapper">
        <a class="btn btn-outline-success btn-dark " href="{% url 'notes:create_note' %}" type="button">
            Create new NOTE
        </a>
    </div>
{% endblock %}

templates/index.html
<!-- templates/index.html -->

{% extends "base.html" %}

{% block content %}
    <section class="text-center mb-4">
        <h1> Welcome to the NOTES APP!</h1>
    </section>
{% endblock %}

templates/signup.html
{% extends 'base.html' %}

{% block content %}
    <div class="container pt-5 pb-5">
        <div class="row">
            <div class="col-sm-20 col-md-7 col-lg-5 mx-auto">
                <div class="card card-signin d-inline-block bg-dark text-lg-center">
                    <div class="card-header bg-transparent text-white-50">
                        <h1><b> Sign up here...</b></h1>
                    </div>
                    <div class="card-body bg-dark pt-4 pb-5 ">
                        <form method="post">
                            {% csrf_token %}
                            <div class="form-label-group col-sm-20 pb-2">
                                <input type="text" name="username" class="form-control" placeholder="Username" required
                                       autofocus>
                            </div>

                            <div class="form-label-group col-sm-20 pb-2">
                                <input name="password1" type="password" class="form-control" placeholder="Password"
                                       required
                                       autofocus>
                            </div>

                            <div class="form-label-group col-sm-20 pb-4">
                                <input name="password2" type="password" class="form-control"
                                       placeholder="Password confirmation"
                                       required
                                       autofocus>
                            </div>

                            <div class="form-control-file">
                                <button type="submit" class="btn btn-success btn-lg col-md-5">
                                    Submit
                                </button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}